### ISSUE TITLE
maybe a little mistake

### ISSUE THREAD

**Issue by lambor** [soimort/wiki#1]
[https://github.com/soimort/wiki/blob/db0acd0f2f7ee6964f3e9ec46254ba6a1e623b1c/unix/cli/src.md#get-the-size-of-a-directory](url)

> In terms of kilobytes:
> 
> $ du -hs foo/bar | cut -f1
> Or: (in human-readable format)
> 
> $ du -s foo/bar | cut -f1

`man du` 

> -h, --human-readable
>               print sizes in human readable format (e.g., 1K 234M 2G)

**Comment by soimort** [comment]
Good catch. Thanks!
